/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2020-11-13 04:50:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	static String fmtNull(String s){
		if(s == null || s.equals("")){
			s = "";
		}
		return s;

	}


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/incFile.jsp", Long.valueOf(1605242901286L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<title>管理者ログイン</title>\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/JavaScript\" src=\"incScript.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/JavaScript\">\r\n");
      out.write("\t\t\t<!--\r\n");
      out.write("\t\t\t\tfunction dataCheck(obj){\r\n");
      out.write("\t\t\t\t\t//1.名前、パスワードの未入力チェック\r\n");
      out.write("\t\t\t\t\tif(obj.elements[0].value.length == 0 || obj.elements[1].value.length == 0){\r\n");
      out.write("\t\t\t\t\t\t//1.名前、パスワードが未入力の時、アラーとを表示し、\"false\"をリターンする。\r\n");
      out.write("\t\t\t\t\t\talert(\"お名前、パスワードは必ず入力してください。\");\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t//2.名前、パスワードがともに入力されていた時、\"true\"をリターンする。\r\n");
      out.write("\t\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t//-->\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\t<!--\r\n");
      out.write("\t\t\t\t* \t\t{padding: 5px;\r\n");
      out.write("\t\t\t\t\t\tmargin: 0px;}\r\n");
      out.write("\t\t\t\tbody   \t{text-align: center;}\r\n");
      out.write("\t\t\t\th2\t   \t{width: 500px;\r\n");
      out.write("\t\t\t\t\t\tborder: 1px solid #000000;\r\n");
      out.write("\t\t\t\t\t\tbackground: #8FBC8F;\r\n");
      out.write("\t\t\t\t\t\tmargin: 0 auto;}\r\n");
      out.write("\t\t\t\ttable  \t{width: 510px;\r\n");
      out.write("\t\t\t\t\t\tbackground: white;\r\n");
      out.write("\t\t\t\t\t\tborder: 1px #000000;\r\n");
      out.write("\t\t\t\t\t\tborder-collapse: collapse;\r\n");
      out.write("\t\t\t\t\t\tmargin: auto;}\r\n");
      out.write("\t\t\t\tth \t   \t{width: 150px;\r\n");
      out.write("\t\t\t\t\t\tborder: 1px solid;\r\n");
      out.write("\t\t\t\t\t\tbackground: #8FBC8F;}\r\n");
      out.write("\t\t\t\ttd \t   \t{width: 350px;\r\n");
      out.write("\t\t\t\t\t\tborder: 1px solid;\r\n");
      out.write("\t\t\t\t\t\ttext-align: left;}\r\n");
      out.write("\t\t\t\tp \t   \t{width: 500px;\r\n");
      out.write("\t\t\t\t\t\ttext-align: center;}\r\n");
      out.write("\t\t\t\tdiv\t\t{width: 500px;\r\n");
      out.write("\t\t\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t\t\t\t\tcolor: black;\r\n");
      out.write("\t\t\t\t\t\tmargin: 0 auto;}\r\n");
      out.write("\t\t\t\ttd#sub \t{width: 500px;\r\n");
      out.write("\t\t\t\t\t\tbackground: #8FBC8F;\r\n");
      out.write("\t\t\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\t\t\tborder-color : black;\r\n");
      out.write("\t\t\t\t\t\tcolor : red;}\r\n");
      out.write("\t\t\t\tdiv#sub\t{text-align: left;}\r\n");
      out.write("\t\t\t\tp#boder {width: 500px;\r\n");
      out.write("\t\t\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t\t\t\t\tmargin: 0 auto;}\r\n");
      out.write("\t\t\t-->\r\n");
      out.write("\t\t\t</style>\r\n");
      out.write("\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<h2>管理者ログイン</h2>\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t<div align=\"center\">");
      out.print(fmtNull((String) request.getAttribute("msg")));
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<form name=\"loginForm\" action=\"AdminLoginSvl\" method=\"post\" onsubmit=\"return dataCheck(this);\">\r\n");
      out.write("\t\t\t<table align=\"center\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<th>管理者名</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"admName\" size=\"10\" maxlength=\"10\" style=\"ime-mode: active;\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<th>パスワード</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" name=\"password\" size=\"10\" maxlength=\"8\" style=\"ime-mode: inactive;\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td id=\"sub\" colspan=\"2\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\" 送 信 \" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\r\n");
      out.write("\t\t<p id=\"boder\" align=\"center\"><a href=\"home.jsp\">ホームページ</a></p>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
