/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2020-11-13 04:51:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.User;

public final class review_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.User");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<title>お客様レビュー\r\n");
      out.write("</title>\r\n");
      out.write("<!-- cssのインポート -->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"href=\"homeAction.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"showMenu.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- タイトル用フォントのインポート -->\r\n");
      out.write("<style>\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Limelight&display=swap');\r\n");
      out.write("</style>\r\n");
      out.write("<!-- 日本語レビュー用フォントのインポート -->\r\n");
      out.write("<style>\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=M+PLUS+1p&display=swap');\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

        User user = (User) session.getAttribute("userInfo");

      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("<!--        アコーディオンメニューの表示          -->\r\n");
      out.write("    <div class=\"cp_menu\">\r\n");
      out.write("        ");

            if (user != null) {
        
      out.write("\r\n");
      out.write("        <label for=\"cp_menu_bar1\">ようこそ！");
      out.print(user.getUsrName());
      out.write("様\r\n");
      out.write("        </label> <input type=\"radio\" name=\"radio\" id=\"cp_menu_bar1\" class=\"accordion\" />\r\n");
      out.write("        <ul id=\"link1\">\r\n");
      out.write("            <li><a href=\"UserUpdateSvl\">お客様情報変更</a></li>\r\n");
      out.write("            <li><a href=\"UserDeleteSvl\">脱会手続き</a></li>\r\n");
      out.write("            <li><a href=\"UserLogoffSvl\">ログオフ</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <label for=\"cp_menu_bar3\">ご予約はこちら</label> <input type=\"radio\"\r\n");
      out.write("            name=\"radio\" id=\"cp_menu_bar3\" class=\"accordion\" />\r\n");
      out.write("        <ul id=\"link3\">\r\n");
      out.write("            <li><a href=\"ReserveListSvl\">ご予約一覧</a></li>\r\n");
      out.write("            <li><a href=\"ReserveInsertSvl\">新規予約</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        ");

            } else {
        
      out.write("\r\n");
      out.write("        <label for=\"cp_menu_bar1\">ようこそ！ゲスト様</label> <input type=\"radio\"\r\n");
      out.write("            name=\"radio\" id=\"cp_menu_bar1\" class=\"accordion\" />\r\n");
      out.write("        <ul id=\"link1\">\r\n");
      out.write("            <li><a href=\"userLogin.jsp\">ログイン</a></li>\r\n");
      out.write("            <li><a href=\"userInsert.jsp\">新規入会</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"display: flex;margin: 0 auto;\">\r\n");
      out.write("\r\n");
      out.write("<div  style=\"float:left; width:10%;\r\n");
      out.write("         padding: 5px; text-align:center;margin: 0 auto;\">\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write(" <a href=\"home.jsp\">\r\n");
      out.write(" <img src=\"./img/logo.png\"  width=\"200px\"/ >\r\n");
      out.write(" </a>\r\n");
      out.write("    </div>\r\n");
      out.write("<div  style=\"float:right; width:70%;\r\n");
      out.write("         padding: 5px; text-align:left;margin: 0 auto;\">\r\n");
      out.write("<div1 style=\"font-size:x-large;\">\r\n");
      out.write("<font class=\"left\"  color=\"#FFFAF0\" >\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("\r\n");
      out.write("        <h1>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ristorante Idealle</h1>\r\n");
      out.write("</font>\r\n");
      out.write("</div1>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("\r\n");
      out.write("<nav>\r\n");
      out.write("<div class=\"buttons-coll\">\r\n");
      out.write("  <ul class=\"clearfix\" style=\"text-align:center ;\">\r\n");
      out.write("    <li >\r\n");
      out.write("        <button class=\"custom-btn btn-2\">\r\n");
      out.write("        <a href=\"home.jsp\">Top</button></a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li >\r\n");
      out.write("        <button class=\"custom-btn btn-2\">\r\n");
      out.write("        <a href=\"ShowMenuSvl\">Menu</button></a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li >\r\n");
      out.write("        <button class=\"custom-btn btn-2\">\r\n");
      out.write("        <a href=\"information.jsp\">About</button></a>\r\n");
      out.write("    </li>\r\n");
      out.write("     <li >\r\n");
      out.write("        <button class=\"custom-btn btn-2\">\r\n");
      out.write("        <a href=\"review.jsp\">Review</button></a>\r\n");
      out.write("    </li>\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("<main>\r\n");
      out.write("<div style=\"display: flex;margin: 0 auto;\">\r\n");
      out.write("<div  style=\"float:left; width:40%;\r\n");
      out.write("         padding: 10px; text-align:center;   margin: 0 auto;\">\r\n");
      out.write("<font class=\"left\" size=\"4\" color=\"#FFFAF0\" ><p>\r\n");
      out.write("【Toro様】素敵な店主</p></font>\r\n");
      out.write("<font size=\"3\" color=\"#FFFAF0\" ><span class=\"firstStr\">みどりの町の住宅街にある隠れ家的なお店。 <br/>\r\n");
      out.write("静かな環境で外観や内装もすごく良い雰囲気です。 <br/>\r\n");
      out.write("本日はランチにお邪魔しました。Bランチを注文。 <br/>\r\n");
      out.write("前菜2品、メインディッシュ,デザート、 <br/>\r\n");
      out.write("ドリンクは1品を選べます。 <br/>\r\n");
      out.write("パンはおかわり出来ます。 <br/>\r\n");
      out.write("料理はリーズナブルで見た目の彩りもキレイで美味しいです。 <br/>\r\n");
      out.write("焼きたてのパンも香ばしく、デザートも美味しくいただきました。 <br/>\r\n");
      out.write("ランチBOX、オードブルなどのテイクアウトもされてます。 <br/>\r\n");
      out.write(" (訪問：2020/08/25) <br/>\r\n");
      out.write("</span>\r\n");
      out.write("</font>\r\n");
      out.write("    </div>\r\n");
      out.write("<div  style=\"float:right; width:40%;\r\n");
      out.write("         padding: 10px; text-align:center;   margin: 0 auto;\">\r\n");
      out.write("<font class=\"left\" size=\"4\" color=\"#FFFAF0\" ><p>\r\n");
      out.write("【kino様】素敵な店主の娘</p></font>\r\n");
      out.write("<font size=\"3\" color=\"#FFFAF0\" ><span class=\"firstStr\">\r\n");
      out.write("以前、記念日に伺い お店の雰囲気が良くて<br/>\r\n");
      out.write("落ち着いてフレンチをいただけたので、<br/>\r\n");
      out.write("今回は母とランチで再訪です。<br/>\r\n");
      out.write("私はお肉ランチ、母は魚ランチで前菜が２種選べる<br/>\r\n");
      out.write("コースにしました。前菜が凄すぎました。<br/>\r\n");
      out.write("エスカルゴを初めていただきましたが、<br/>\r\n");
      out.write("すごく柔らかくとろける食感で美味しかったです。<br/>\r\n");
      out.write("鮎を使った前菜も香りが良くかなり美味しかったです。<br/>\r\n");
      out.write("日常を少し忘れ、美味しいものに話を咲かせることが出来ました。<br/>\r\n");
      out.write(" (訪問：2020/07/30)\r\n");
      out.write(" </span>\r\n");
      out.write("</font>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<hr/>\r\n");
      out.write("<div style=\"display: flex;margin: 0 auto;\">\r\n");
      out.write("<div  style=\"float:left; width:40%;\r\n");
      out.write("         padding: 10px; text-align:center;   margin: 0 auto;\">\r\n");
      out.write("<font class=\"left\" size=\"4\" color=\"#FFFAF0\" ><p>\r\n");
      out.write("【ぴなぷ様】素敵なムスコ</p></font>\r\n");
      out.write("<font size=\"3\" color=\"#FFFAF0\" ><span class=\"firstStr\">\r\n");
      out.write("先ずはサラダ。サラダというより前菜です。<br/>\r\n");
      out.write("一つ一つ丁寧に盛り付けてあり、味付けや素材の味の違いを楽しめます。<br/>\r\n");
      out.write("スープは人参のポタージュ。美味しいです。<br/>\r\n");
      out.write("次はメインの鶏肉。パリパリの皮でgood！<br/>\r\n");
      out.write("付け合わせのキャベツは甘く、ジャガイモはねっとりとしていてとても合います。<br/>\r\n");
      out.write("デザートは、レモンのタルトとバニラアイス。\r\n");
      out.write("<br/>レモンピールの苦味が絶妙、その辺の<br/>\r\n");
      out.write("ケーキ屋さんのよりも何倍も美味しいです。\r\n");
      out.write("<br/>バニラアイスはバニラの風味が豊かに香り、<br/>\r\n");
      out.write("タルトと一緒に食べたらまた美味しかったです。<br/>\r\n");
      out.write("絶対リピート、また来ます。お店の内装も雰囲気も好み。<br/>\r\n");
      out.write("大切なお店とさせて頂きたいと思います。<br/>\r\n");
      out.write(" (訪問：2020/03/03)\r\n");
      out.write("</span>\r\n");
      out.write("</font>\r\n");
      out.write("    </div>\r\n");
      out.write("<div  style=\"float:right; width:40%;\r\n");
      out.write("         padding: 10px; text-align:center;   margin: 0 auto;\">\r\n");
      out.write("<font class=\"left\" size=\"4\" color=\"#FFFAF0\" ><p>\r\n");
      out.write("【のん様】素敵な店主の愛人</p></font>\r\n");
      out.write("<font size=\"3\" color=\"#FFFAF0\" ><span class=\"firstStr\">\r\n");
      out.write("平日のランチでお邪魔しました(^^)メインが選べる2000円のコースにしました。どれも美味しそうでかなり悩みます！フレンチなのに豚足?と思い、豚足の包んだような物をチョイス。運ばれてきて、まず、香りにビックリです。中華を思わせるような、八角の香りが漂います。添えてある野菜もまさかのニラ！味は中華なのに見た目はフレンチ〜、でも香りは中華、でもナイフとフォークで食べてる！軽いパニックになりました（笑）オードブルも一つ一つがとても手がこんでいて、特にキッシュは焼きたてサクサクで絶品です。デザートは、温かいタルトにアイスクリームが添えられていて(他にも数種類アリ)ランチとは思えないクオリティでした。コレで2000円はお得です☆値段以上の満足感でした。 (訪問：2015/08/27)\r\n");
      out.write(" </span>\r\n");
      out.write("</font>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/><br/>\r\n");
      out.write("<br/>\r\n");
      out.write("</main>\r\n");
      out.write("<footer>\r\n");
      out.write("<nav>\r\n");
      out.write("            <ul style=\"text-align:center\">\r\n");
      out.write("              <li class=”current”><div><a href=”#”> <a href=\"https://www.instagram.com/?hl=ja\"><img src=\"./img/200520133708-5ec4b3f4bb74a.png\"/></a></a></div></li>\r\n");
      out.write("              <li><div><a href=”#”><a href=\"https://ja-jp.facebook.com/\" ><img src=\"./img/200528153054-5ecf5a9ebd033.png\"/></a></div></li>\r\n");
      out.write("              <li><div><a href=”#”><a href=\"https://www.ubereats.com/jp\"><img src=\"./img/200529091516-5ed0541485804.png\"/></a></a></div></li>\r\n");
      out.write("              <li><div><a href=”#”><a href=\"https://www.foxnews.com/\"><img src=\"./img/200529090425-5ed051899491f.png\"/></a></a></div></li>\r\n");
      out.write("              <li><div><a href=”#”><a href=https://thebase.in/\"\"><img src=\"./img/200529092244-5ed055d4afce8.png\"/></a></a></div></li>\r\n");
      out.write("             </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("<hr>\r\n");
      out.write("<font class=\"right\" size=\"1\" color=\"#FFFAF0\" ><p>\r\n");
      out.write("         【Ristorante Idealle】<br/>\r\n");
      out.write("〒060-0005<br/>\r\n");
      out.write("札幌市中央区北５条西2−５<br/>\r\n");
      out.write("JRタワーオフィスプラザさっぽろ19F<br/>\r\n");
      out.write("TEL: 011-206-1663 <br/>\r\n");
      out.write("Mail: sapporo@kenschool.jp<br/>\r\n");
      out.write("</p>\r\n");
      out.write("</font>\r\n");
      out.write("<div style=\"text-align: right;\" >\r\n");
      out.write(" <a href=\"adminLogin.jsp\" >●管理者ログイン</a>\r\n");
      out.write("\r\n");
      out.write("<br/>\r\n");
      out.write("<font  color=\"#FFFAF0\" size=\"2\">※Created by Kamiyama,Kawata,Nagata,Yanagisawa,Yokoi,Mizuki\r\n");
      out.write("<br/>\r\n");
      out.write("※Unauthorized copying of the All of this site are strictly prohibited.\r\n");
      out.write("<br/>\r\n");
      out.write("</font>\r\n");
      out.write(" </div>\r\n");
      out.write("</footer>\r\n");
      out.write(" </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
